djangoShow/appeals/urls.py
from django.urls import path
from .views import *

app_name = 'appeals'
urlpatterns = [
    path('', index, name='index'),
    path('add_complaint/', add_complaint, name='add_complaint'),
]

djangoShow/logic/urls.py
from django.urls import path
from .views import *

app_name = 'logic'
urlpatterns = [
    # стартовая
    path('', start_page, name='start_page'),
]

djangoShow/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django_telegrambot.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logic.urls')),
    path('appeals/', include('appeals.urls')),
    url(r'^', include('django_telegrambot.urls')),
]

djangoShow/appeals/models.py
import datetime
from django.db import models
from django.utils import timezone


class Complaint(models.Model):
    text = models.CharField('вопрос', max_length=200)
    answer = models.CharField('ответ', max_length=200)

    def __str__(self):
        return f"{self.text} | {self.answer}"

    class Meta:
        verbose_name = 'Предложение'
        verbose_name_plural = 'Предложения'

djangoShow/logic/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Rank(models.TextChoices):
    """Звания, которые могут быть у курируемых"""
    ONE = '01', _('Рядовой соботыльник')
    TWO = '02', _('Младший сержант бота')
    THREE = '03', _('Сержант олимпиад')
    FOUR = '04', _('Старшина перечней')
    FIVE = '05', _('Товарищ прапорщик')
    SIX = '06', _('Старший соботыльник')
    SEVEN = '07', _('Лейтенант учёбы')
    EIGHT = '08', _('Капитан региона')
    NINE = '09', _('Майор тайм-менеджмента')
    TEN = '10', _('Полковник-бвишник')
    ELEVEN = '11', _('Генерал всерос(с)а')
    TWELVE = '12', _('Магистр книг и пособий')
    THIRTEEN = '13', _('Повелитель бота')
    FOURTEEN = '14', _('Император всея Бота и Учёбы')


class WeekDay(models.TextChoices):
    """День недели"""
    MONDAY = '1', _('понедельник')
    TUESDAY = '2', _('вторник')
    WEDNESDAY = '3', _('среда')
    THURSDAY = '4', _('четверг')
    FRIDAY = '5', _('пятница')
    SATURDAY = '6', _('суббота')
    SUNDAY = '7', _('воскресенье')


class Group(models.TextChoices):
    """Группа"""
    PRO = 'P', _('Pro')
    LITE = 'L', _('Lite')


class CuratorProfile(models.Model):
    """
        Профиль куратора (для того, чтобы не возится с User тут лежит вся нужная инфа)
        user.username - ник в телеге (обязательное поле)
        user.first_name - имя
        user.last_name - фамилия
        user.email - мыло (хз зачем, но оно есть)
        user.password - хэш и метаданные о пароле (обязательное поле)
        user.is_staff - булево, показывает, что это куратор
        user.is_active - булево, позволяет банить учетки (не перманентно)
        user.is_superuser - не трогать, на будующее
        user.last_login - не трогать, на будующее
        user.date_joined - дата создания аккаунта
    """

    notes = models.TextField('заметки', blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='сuratorProfile', null=True)

    def __str__(self):
        return f'{self.user.username} {self.user.get_full_name()}'

    class Meta:
        verbose_name = 'Куратор'
        verbose_name_plural = 'Кураторы'


class PadawanProfile(models.Model):
    """
        Профиль человека (для того, чтобы не возится с User тут лежит вся нужная инфа)
        user.username - ник в телеге (обязательное поле)
        user.first_name - имя
        user.last_name - фамилия
        user.email - мыло (хз зачем, но оно есть)
        user.password - хэш и метаданные о пароле (обязательное поле)
        user.is_staff - булево, показывает, что это куратор
        user.is_active - булево, позволяет банить учетки (не перманентно)
        user.is_superuser - не трогать, на будующее
        user.last_login - показывает время последних действий (для чека подъема)
        user.date_joined - дата создания аккаунта
    """

    telephone = models.CharField('телефон', max_length=16, blank=True)
    notes = models.TextField('заметки', blank=True)
    rank = models.CharField('звание', choices=Rank.choices, default=Rank.ONE, max_length=2)
    off_date = models.DateField('окончание оплаченного периода', auto_now=True)
    weekend = models.CharField('выходной', choices=WeekDay.choices, default=WeekDay.SUNDAY, max_length=1)
    group = models.CharField('группа', choices=Group.choices, default=Group.LITE, max_length=1)
    utc = models.IntegerField('временной сдвиг', default=3, validators=[MinValueValidator(-12), MaxValueValidator(12)])
    rating = models.IntegerField('рейтинг', default=0, validators=[MinValueValidator(-20)])
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='padawanProfile', null=True)
    curator = models.ForeignKey(CuratorProfile, on_delete=models.SET_NULL, related_name='padawans', null=True)

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = 'Подаван'
        verbose_name_plural = 'Подваны'
        ordering = ["-off_date"]


class Code(models.Model):

    days = models.IntegerField('время', default=0, validators=[MinValueValidator(0)])
    activations = models.IntegerField('активации', default=0, validators=[MinValueValidator(0)])
    text = models.SlugField('текст')
    users = models.ManyToManyField(PadawanProfile, blank=True, related_name='activatedCodes')

    def __str__(self) -> str:
        return f'{self.text} на {self.days} сталось: {self.activations - len(self.users.all())}'

    class Meta:
        verbose_name = 'Код'
        verbose_name_plural = 'Коды'
        ordering = ["-days"]

djangoShow/appeals/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from .models import Complaint
from django.utils import timezone
from django.db.models import Q


def index(request):
    latest_complaint_list = Complaint.objects.all().exclude(answer="Нет ответа").all().order_by('-id')
    return render(request, 'appeals/list.html', {'latest_complaint_list': latest_complaint_list})


def add_complaint(request):
    Complaint(text=request.POST['text'], answer="Нет ответа").save()
    return HttpResponseRedirect(reverse('appeals:index'))

djangoShow/logic/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import *
from django.core.exceptions import PermissionDenied


def start_page(request):
    return render(request, 'base.html', {'user': request.user})

djangoShow/logic/templates/appeals/list.html
{% extends 'base.html' %} {% block title %}Последние предложения{% endblock %} {% block extra_css%}
<style>
    .auth {
        color: #ff7f29;
        font-family: Nunito Sans;
        font-size: 28px;
        text-align: center;
        margin-top: 100px;
    }
    
    .text_mess {
        margin-bottom: 50px;
        margin-top: 50px;
        margin-left: 100px;
        margin-right: 100px;
        color: #a81fe7;
        font-family: Nunito Sans;
        font-size: 28px;
        text-align: left;
    }
    
    .messages {
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px 10px;
        width: 55%;
        border: 3px solid white;
        border-radius: 50px 0px 50px 0px;
        background-color: rgba(255, 255, 255, 0.5);
    }
    
    .send {
        margin: 30px;
        width: 200px;
        height: 100px;
        transition: all .2s ease-in-out .1s;
        background-color: #a81fe7;
        color: white;
        font-size: 22px;
        padding: 20px;
        border-radius: 50px 0px 50px 0px;
        border: 2px solid green;
        padding: 10px;
        text-align: center;
    }
    
    .main_container {
        position: relative;
        background-color: #0dffc1;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    .textarea {
        margin: 30px;
        width: 60%;
        border: 3px solid white;
    }
    
    .questions {
        position: relative;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    .btn {
        position: relative;
        display: flex;
        justify-content: space-around;
    }
</style>
{% endblock %} {% block content %} {% if latest_complaint_list %} {% for a in latest_complaint_list %}
<div class="messages">
    <div class="auth">
        <h1>{{a.text}}</h1>
    </div>
    <div class="text_mess">
        <h3>{{a.answer}}</h3>
    </div>
</div>
{% endfor %} {% else %} Предложения не найдены {% endif %}


<form action="{% url 'appeals:add_complaint' %}" method="POST" class="messages questions">
    {% csrf_token %}
    <textarea class="textarea" name="text" required="" placeholder="              Текст предложения" cols="30" rows="10"></textarea><br>
    <div class="btn">
        <button class="send" type="submit">Оставить предложение</button>
    </div>
</form>
{% endblock %}

djangoShow/logic/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>

    <meta charset="UTF-8">
    <title> Тест </title>

</head>

<body>
    Тест
</body>

</html>

djangoShow/logic/templates/logic/account_settings.html
{% extends 'base.html' %} {% block title %}Настройки{% endblock %} {% block extra_css %}
<style>
    .quests_container {
        width: 600px;
        height: 60px;
        transition: all .2s ease-in-out .1s;
        color: white;
        position: relative;
        display: block;
        font-family: Nunito+Sans;
        font-size: 30px;
        padding: 20px;
        background-color: #ff7f29;
        border-radius: 50px 0px 50px 0px;
        margin-top: 5px;
        border: 2px solid green;
        padding: 10px;
        text-align: center;
    }
    
    .quests_container:hover {
        color: red;
        transition: all .3s ease;
        transform: scale(1.06);
        background-color: white;
    }
    
    .quests_container:active {
        color: green;
        transition: all .02s ease;
        transform: scale(.96);
    }
    
    .main_container {
        position: relative;
        background-color: #0dffc1;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    .container {
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px 10px;
        width: 55%;
        border: 3px solid white;
        border-radius: 50px 0px 50px 0px;
        background-color: rgba(255, 255, 255, 0.5);
        position: relative;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    .messages {
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px 10px;
        width: 75%;
        border: 3px solid white;
        border-radius: 50px 0px 50px 0px;
        background-color: rgba(255, 255, 255, 0.5);
    }
    
    .send {
        margin: 30px;
        width: 300px;
        height: 100px;
        transition: all .2s ease-in-out .1s;
        background-color: #a81fe7;
        color: white;
        font-size: 22px;
        padding: 20px;
        border-radius: 50px 0px 50px 0px;
        border: 2px solid green;
        padding: 10px;
        text-align: center;
    }
    
    .textarea {
        margin: 30px;
        width: 600px;
        height: 250px;
        border: 3px solid white;
        font-size: 20px;
    }
    
    .questions {
        position: relative;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    .text_mess,
    .text {
        margin-bottom: 50px;
        margin-top: 50px;
        margin-left: 10px;
        margin-right: 100px;
        color: #a81fe7;
        font-family: Nunito Sans;
        font-size: 28px;
        text-align: left;
    }
    
    .text {
        color: #ff7f29;
        font-size: 35px;
    }
    
    input {
        height: 60px;
        width: 200px;
        font-size: 20px;
    }
    
    .textarea {
        margin: 30px;
        width: 60%;
        height: 250px;
        border: 3px solid white;
        font-size: 20px;
    }
    
    .check {
        width: 25px;
        background-color: #ff7f29;
    }
    
    .inline {
        margin-top: -60px;
        display: flex;
        justify-content: space-around;
        align-items: center;
    }
    
    .large {
        font-size: 30px;
    }
</style>
{% endblock %} {% block content %}
<div class="container">
    <form class="messages questions" action="{% url 'logic:change_password' %}" method="POST">
        {% csrf_token %}
        <input type="password" required placeholder="  Новый пароль" name="password">
        <button class="send" type="submit">Изменить пароль</button>
    </form>
    <hr>
    <form class="messages questions" action="{% url 'logic:leave_article' %}" method="POST">
        {% csrf_token %}
        <input type="text" required placeholder="  Название вопроса" name="title"> <br>
        <textarea class="textarea" name="text" required="" placeholder="    Текст вопроса" cols="30" rows="10"></textarea>
        <div class="text">
            <h5>Тема:</h5>
        </div>
        {% for c in Topic.choices %}
        <div class="inline">
            <input class="check" name="topic" type="radio" value="{{ c.0 }}">
            <div class="text_mess">
                <h5>{{ c.1 }}</h5>
            </div>
        </div> {% endfor %}
        <div class="text">
            <h5>Комментарии:</h5>
        </div>
        <div class="inline">
            <input class="check" name="comments" type="radio" value="PU">
            <div class="text_mess">
                <h5>PUBLIC</h5>
            </div>
        </div>
        <div class="inline">
            <input class="check" name="comments" type="radio" value="PR" checked>
            <div class="text_mess">
                <h5>PRIVATE</h5>
            </div>
        </div>

        <div class="text">
            <h5>Доступ к вопросу:</h5>
        </div>
        <div class="inline">
            <input class="check" name="access" type="radio" value="PU">
            <div class="text_mess">
                <h5>PUBLIC</h5>
            </div>
        </div>
        <div class="inline">
            <input class="check" name="access" type="radio" value="PR" checked>
            <div class="text_mess">
                <h5>PRIVATE</h5>
            </div>
        </div>
        <button class="send" type="submit"> Продолжить создание вопроса </button>
    </form>
    <hr> {% if user.article_set.all %}
    <div class="text_mess large">
        <h3>Ваши вопросы:</h3>
    </div> {% for a in user.article_set.all %}
    <div>
        <a class="quests_container" href="{% url 'logic:detail_article' a.id %}">{{ a.title }} | {{ a.get_topic_display }} | {{ a.get_access_display }}</a>
    </div>
    {% endfor %} {% else %}
    <div>
        <a class="quests_container">Вопросы не найдены</a>
    </div>{% endif %}
</div>{% endblock %}

djangoShow/logic/templates/logic/article_list.html
{% extends 'base.html' %} {% block title %} Последние вопросы {% endblock %} {% block extra_css %}
<style>
    .quests_container {
        width: 30%;
        left: 52%;
        transition: all .2s ease-in-out .1s;
        color: white;
        position: relative;
        display: block;
        font-family: Nunito+Sans;
        font-size: 30px;
        padding: 20px;
        background-color: #ff7f29;
        border-radius: 50px 0px 50px 0px;
        margin-top: 5px;
        border: 2px solid green;
        padding: 10px;
        text-align: center;
    }
    
    .quests_container:hover {
        color: red;
        transition: all .3s ease;
        transform: scale(1.06);
        background-color: white;
    }
    
    .quests_container:active {
        color: green;
        transition: all .02s ease;
        transform: scale(.96);
    }
</style>
{% endblock %} {% block content %}
<form class="messages questions" action="{% url 'logic:slug_search' %}" method="GET">
    {% csrf_token %}
    <input type="text" required placeholder="  Поиск по slug" name="slug">
    <button class="send" type="submit"> Найти </button>
</form>
{% if list %} {% for a in list %}
<div>
    <a class="quests_container" href="{% url 'logic:detail_article' a.id %}"> {{ a.title }} | {{ a.get_topic_display }} </a>
</div>
{% endfor %} {% else %}
<div>
    <a class="quests_container">Вопросы не найдены</a>
</div>
{% endif %} {% endblock %}

djangoShow/logic/templates/logic/change_article.html
{% extends 'base.html' %} {% block title %} {{ article.title }} {% endblock %} {% block extra_css %}
<style>
    .main_container {
        position: relative;
        background-color: #0dffc1;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    .content {
        padding: 30px 10px;
        width: 55%;
        border: 3px solid white;
        border-radius: 50px 0px 50px 0px;
        background-color: rgba(255, 255, 255, 0.5);
    }
    
    .container {
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px 10px;
        width: 55%;
        border: 3px solid white;
        border-radius: 50px 0px 50px 0px;
        background-color: rgba(255, 255, 255, 0.5);
        position: relative;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    .title_cont,
    .auth {
        color: #ff7f29;
        font-family: Nunito Sans;
        font-size: 30px;
        text-align: center;
    }
    
    .auth {
        margin-top: 7px;
    }
    
    .text_mess,
    .text {
        margin-bottom: 20px;
        margin-top: 10px;
        color: #a81fe7;
        margin-left: 10px;
        margin-right: 10px;
        font-family: Nunito Sans;
        font-size: 28px;
        text-align: left;
    }
    
    .text_mess_input {
        font-size: 20px;
        margin-bottom: 50px;
        margin-top: 50px;
        color: #a81fe7;
        margin-left: 10px;
        margin-right: 10px;
        font-family: Nunito Sans;
        text-align: left;
    }
    
    .text {
        color: #ff7f29;
        font-size: 30px;
    }
    
    .date_cont {
        color: #ff7f29;
        font-family: Nunito Sans;
        font-size: 22px;
        text-align: right;
        margin-right: 100px;
    }
    
    .messages {
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px 10px;
        width: 75%;
        border: 3px solid white;
        border-radius: 50px 0px 50px 0px;
        background-color: rgba(255, 255, 255, 0.5);
    }
    
    .send {
        margin: 30px;
        width: 300px;
        height: 100px;
        transition: all .2s ease-in-out .1s;
        background-color: #a81fe7;
        color: white;
        font-size: 22px;
        padding: 20px;
        border-radius: 50px 0px 50px 0px;
        border: 2px solid green;
        padding: 10px;
        text-align: center;
    }
    
    .textarea {
        margin: 30px;
        width: 60%;
        height: 250px;
        border: 3px solid white;
        font-size: 20px;
    }
    
    .questions {
        position: relative;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    .btn {
        position: relative;
        display: flex;
        justify-content: space-around;
    }
    
    .form {
        width: 80%;
        border-bottom: 10px dashed white;
        padding-top: 30px;
        margin-top: 50px;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    
    input {
        height: 60px;
        width: 200px;
        font-size: 20px;
    }
    
    .check {
        width: 3%;
        background-color: #ff7f29;
    }
    
    .article_text {
        display: block;
    }
    
    .art_text {
        display: flex;
        justify-content: space-around;
        align-items: center;
    }
    
    .a_text {
        text-align: center;
        width: 120%;
        margin-left: -70px;
        margin-bottom: 130px;
    }
    
    .inline {
        margin-top: -60px;
        display: flex;
        justify-content: space-around;
        align-items: center;
    }
</style>
{% endblock %} {% block content %}
<div class="content">
    <div class="title_cont">
        <h1>{{ article.title }} | {{ article.get_access_display }}</h1>
    </div>
</div>
<div class="container">
    <form class="form" method="POST">
        {% csrf_token %} {% if article.is_private %}
        <button class="send" type="submit" formaction="{% url 'logic:make_public' article.id %}"> Отправить на модерацию </button> {% else %}
        <button class="send" type="submit" formaction="{% url 'logic:make_private' article.id %}"> Сделать приватной </button> {% endif %}
    </form>
    <form class="form article_text" action="{% url 'logic:change_title' article.id %}" method="POST">
        {% csrf_token %}

        <div class="art_text">
            <input type="text" required placeholder="  Новое название" name="title">
            <button class="send" type="submit"> Изменить название </button>
        </div>
    </form>
    <form class="form" action="{% url 'logic:change_text' article.id %}" method="POST">
        {% csrf_token %}
        <div>
            <div class="text a_text">
                <h5>{{ article.text }}</h5>
            </div>
            <div class="inline">
                <textarea class="textarea" name="text" required placeholder="    Новый текст" cols="30" rows="10"></textarea>
                <button class="send" type="submit"> Изменить текст </button>
            </div>
        </div>
    </form>
    <form class="form" method="POST">
        {% csrf_token %}
        <div class="text">
            <h5>Комментарии: {{ article.get_comment_access_display }}</h5>
        </div> {% if article.can_make_publish %}
        <button class="send" type="submit" formaction="{% url 'logic:make_comments_private' article.id %}"> Сделать комментарии только приватными </button> {% else %}
        <button class="send" type="submit" formaction="{% url 'logic:make_comments_public' article.id %}"> Разрешить отправлять комментарии на модерацию </button> {% endif %}
    </form>
    <form class="form" action="{% url 'logic:change_topic' article.id %}" method="POST">
        {% csrf_token %} {% for c in Topic.choices %} {% if article.topic == c.0 %}
        <input class="check" name="topic" type="radio" value="{{ c.0 }}" checked>
        <div class="text_mess_input">
            <h5>{{ c.1 }}</h5>
        </div> {% else %}
        <input class="check" name="topic" type="radio" value="{{ c.0 }}">
        <div class="text_mess_input">
            <h5>{{ c.1 }}</h5>
        </div>
        {% endif %} {% endfor %}
        <button class="send" type="submit"> Изменить тему </button>
    </form>
    <div class="messages questions">
        <div class="text">
            <h4> Дата: </h4>
        </div>
        <div class="text_mess">
            <h5> {{ article.pub_date }} </h5>
        </div>
        <div class="text">
            <h4> Авторы: </h4>
        </div>
        {% if article.authors.all %} {% for author in article.authors.all %}

        <div class="auth">
            <h3>{{ author.username }} </h1>
        </div>{% endfor %} {% else %}
        <div class="text">
            <h5>Нет авторов</h5>
        </div>
        {% endif %}
    </div>
    <form class="form" action="{% url 'logic:add_author' article.id %}" method="POST">
        {% csrf_token %}
        <input type="text" required placeholder="  Username автора" name="username" />
        <button class="send" type="submit"> Добавить автора </button>
    </form>
    {% if article.slug %} <a href="{% url 'logic:slug_access' article.slug %}" target="_blank"> Сcылка </a> {% else %} Введите slug для доступа по ссылке {% endif %}
    <form class="form" action="{% url 'logic:change_slug' article.id %}" method="POST">
        {% csrf_token %}
        <input type="text" required placeholder="  Новый slug" name="slug" /><br>
        <button class="send" type="submit"> Изменить slug </button>
    </form>
    {% if article.questions %} {% for question in article.questions %}
    <form class="form" action="{% url 'logic:change_question_text' article.id question.id %}" method="POST">
        {% csrf_token %}
        <div class="text">
            <h5>{{ question.text }}</h5>
        </div>
        <input type="text" required placeholder="  Новый текст" name="text" />
        <button class="send" type="submit"> Изменить текст </button>
    </form>
    <form class="form" action="{% url 'logic:delete_question' article.id question.id %}" method="POST">
        {% csrf_token %}
        <button class="send" type="submit"> Удалить вопрос </button>
    </form>

    <form class="form" action="{% url 'logic:change_question_type' article.id question.id %}" method="POST">
        {% csrf_token %} {% for c in Type.choices %} {% if question.type == c.0 %}
        <input class="check" name="type" type="radio" value="{{ c.0 }}" checked>
        <div class="text_mess">
            <h5>{{ c.1 }}</h5>
        </div> {% else %}
        <input class="check" name="type" type="radio" value="{{ c.0 }}">
        <div class="text_mess">
            <h5>{{ c.1 }}</h5>
        </div> {% endif %} {% endfor %}
        <button class="send" type="submit"> Изменить тип </button>
    </form>
    {% if question.result %}
    <div class="text">
        <h5>Результаты: {{ question.result }}</h5>
    </div> {% endif %} {% if question.is_option %}
    <form class="messages questions" action="{% url 'logic:add_question_option' article.id question.id %}" method="POST">
        {% csrf_token %}
        <input type="text" required placeholder="  Текст варианта" name="text" />
        <button class="send" type="submit"> Добавить вариант </button>
    </form>
    {% if question.option_set.all %} {% for o in question.option_set.all %}
    <form class="messages questions" action="{% url 'logic:delete_option' article.id o.id %}" method="POST">
        {% csrf_token %}
        <div class="text">
            <h5>{{ o.text }}</h5>
        </div>
        <button class="send" type="submit"> Удалить вариант </button>
    </form>
    {% endfor %} {% else %}
    <div class="text">
        <h5>Нет вариантов ответа</h5>
    </div> {% endif %} {% endif %} {% if question.answer_set.all %} {% for a in question.answer_set.all %}
    <form class="messages questions" method="POST">
        {% csrf_token %}
        <div class="auth">
            <h3> {{ a.author_name }}</h1>
        </div>
        {% for o in a.answeroption_set.all %}
        <div class="text">
            <h5>{{ o.text }} </h5>
        </div>
        <button class="send" type="submit" formaction="{% url 'logic:delete_answer' article.id a.id %}"> Удалить ответ </button>
    </form>{% endfor %} {% endfor %} {% else %}
    <div class="text">
        <h5>Нет ответов</h5>
    </div> {% endif %} {% endfor %} {% else %}
    <div class="text">
        <h5>Нет вопросов</h5>
    </div>
    {% endif %}
    <form class="messages questions" action="{% url 'logic:add_question' article.id %}" method="POST">
        {% csrf_token %}
        <button class="send" type="submit"> Добавить вопрос </button>
    </form>
    {% if article.comments %} {% for comment in article.comments %}
    <form class="messages questions" method="POST">
        {% csrf_token %}
        <div class="auth">
            <h3>{{ comment.author_name }} | {{ comment.get_access_display }}</h1>
        </div>
        <div class="text">
            <h5>{{ comment.text }}</h5>
        </div>
        <button class="send" type="submit" formaction="{% url 'logic:delete_comment' article.id comment.id %}"> Удалить комментарий </button> {% if comment.is_private %}
        <button class="send" type="submit" formaction="{% url 'logic:send_comment_to_moderation' article.id comment.id %}"> Отправить на модерацию </button> {% endif %}
    </form>
    {% endfor %} {% else %}
    <div class="text">
        <h5>Нет комментариев</h5>
    </div> {% endif %}
</div> {% endblock %}

djangoShow/logic/templates/logic/login.html
{% extends 'base.html' %} {% block title %} Вход {% endblock %} {% block userName %} Вход {% endblock %} {% block content %}
<form action="{% url 'logic:entry' %}" method="POST">
    {% csrf_token %} Имя: <input type="text" required placeholder="Имя" name="username" /> Пароль: <input type="password" required placeholder="Пароль" name="password" />
    <button type="submit">Войти</button>
</form>
<form action="{% url 'logic:reset_password_from_username' %}" method="POST">
    {% csrf_token %} Имя: <input type="text" required placeholder="Имя" name="username">
    <button type="submit">Сбросить пароль</button>
</form>
<form action="{% url 'logic:reset_password_from_email' %}" method="POST">
    {% csrf_token %} Почта: <input type="email" required placeholder="Почта" name="email">
    <button type="submit">Сбросить пароль</button>
</form>
{% endblock %}

djangoShow/logic/templates/logic/sign.html
{% extends 'base.html' %} {% block title %} Регистрация {% endblock %} {% block userName %} Регистрация {% endblock %} {% block content %}
<form action="{% url 'logic:registration' %}" method="POST">
    {% csrf_token %} Почта: <input type="email" required placeholder="Почта" name="email"> Имя: <input type="text" required placeholder="Имя" name="username">
    <button type="submit">Зарегестрироваться</button>
</form>
{% endblock %}